/* 
 * AT-SPI - Assistive Technology Service Provider Interface 
 * (Gnome Accessibility Project; http://developer.gnome.org/projects/gap)
 *
 * Copyright 2001 Sun Microsystems Inc.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */

#ifndef __ACCESSIBILITY_DESKTOP_DEFINED__
#define __ACCESSIBILITY_DESKTOP_DEFINED__

#include <Accessibility_Accessible.idl>

module Accessibility {
    /**
     * At the moment this is only a marker interface, it acts just like
     * any other Accessible.  In all known implementations, the
     * children are all instances of Application, but this is not
     * guaranteed by this interface.
     **/
    interface Desktop : Accessible {
	  /** \cond
	   * unImplemented:
	   *
	   * placeholders for future expansion.
	   */
	  void unImplemented_ ();
	  void unImplemented2_ ();
	  void unImplemented3_ ();
	  void unImplemented4_ ();
	/** \endcond */
  };
};

#endif
