#ifndef __ACCESSIBILITY_DESKTOP_DEFINED__
#define __ACCESSIBILITY_DESKTOP_DEFINED__

#include <Bonobo.idl>
#include <Accessible.idl>

#if !defined(__ACCESSIBILITY_DESKTOP_COMPILATION) && defined(__ORBIT_IDL__)
%{
#pragma include_defs Desktop.h
%}
#pragma inhibit push
#endif

#pragma inhibit push
#include "Accessible.idl"
#pragma inhibit pop

module Accessibility {
  interface Desktop : Accessible {
    /**
     * At the moment this is only a marker interface, it acts just like
     * any other Accessible.
     **/
  };
};

#if !defined(__ACCESSIBILITY_DESKTOP_COMPILATION) && defined(__ORBIT_IDL__)
#pragma inhibit pop
#endif

#endif
