#ifndef __ACCESSIBILITY_EVENT_DEFINED__
#define __ACCESSIBILITY_EVENT_DEFINED__

#include <Bonobo.idl>

#if !defined(__ACCESSIBILITY_EVENT_COMPILATION) && defined(__ORBIT_IDL__)
%{
#pragma include_defs Accessible.h
#pragma include_defs Event.h
%}
#pragma inhibit push
#endif

#pragma inhibit push
#include "Accessible.idl"
#pragma inhibit pop

module Accessibility
{
  interface Accessible;

  struct Event {
    string type;
    Accessible target;
    long detail1;
    long detail2;
  };

  interface EventListener : Bonobo::Unknown {
    oneway void notifyEvent (in Event e);
  };

};

#if !defined(__ACCESSIBILITY_EVENT_COMPILATION) && defined(__ORBIT_IDL__)
#pragma inhibit pop
#endif

#endif
