/* 
 * AT-SPI - Assistive Technology Service Provider Interface 
 * (Gnome Accessibility Project; http://developer.gnome.org/projects/gap)
 *
 * Copyright 2001 Sun Microsystems Inc.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */

#ifndef _ACCESSIBILITY_MAGNIFIER_IDL
#define _ACCESSIBILITY_MAGNIFIER_IDL

#include <Bonobo.idl>

module Accessibility {
  
  interface Magnifier : Bonobo::Unknown {

    /**
     * #attribute MagFactor: a float indicating the current x and y magnification ratio.
     **/
    attribute float MagFactor;

    /**
     * #attribute SourceDisplay: a @string containing the X display name
     *                            containing the region to be magnified.
     **/
    attribute string SourceDisplay;

    /**
     * #attribute TargetDisplay: a @string containing the X display name
     *                           where the magnifier pixels are to be displayed.
     **/
    attribute string TargetDisplay;

    /**
     * oneway void setROI:
     * Sets the region of interest for the magnifier.
     * @x1: the minimum X coordinate of the ROI bounding box
     * @x2: the maximum X coordinate of the ROI bounding box
     * @y1: the minimum Y coordinate of the ROI bounding box
     * @y2: the maximum Y coordinate of the ROI bounding box
     **/
    oneway void setROI (in long x1, in long y1, in long x2, in long y2);

    /** 
     * void exit:
     * Unmap the current magnifier from the display.
     **/
    void exit ();

  };
};

#endif

